services:
  php-fpm:
    container_name: ${APP_NAME}-php
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php-fpm/php.ini:/etc/php/8.3/fpm/conf.d/php.ini

  db:
    container_name: ${APP_NAME}-db
    image: postgres:16-alpine3.18
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}' ]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database-money-bothub:/data/postgres

  web-server:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db

volumes:
  database-money-bothub:
